services:
  # Postgres database for authentication data
  postgres-auth-db:
    image: postgres:16.2-alpine
    container_name: postgres-auth-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis database for authentication data
  redis-auth-db:
    container_name: redis-auth-db
    image: redis:7.2-alpine
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes # Allow persistence
    ports:
      - "${REDIS_PORT}:6379"

  # Auth microservice - Development (hot reload, source mounted)
  auth-ms-dev:
    container_name: auth-ms-dev
    restart: unless-stopped
    build:
      target: devimage
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - "${PORT_DEV}:${PORT_DEV}"
    environment:
      - HOST=${HOST}
      - PORT=${PORT_DEV}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - REDIS_URL=${REDIS_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_MAIL=${RESEND_FROM_MAIL}
    depends_on:
      - postgres-auth-db
      - redis-auth-db
  # Auth microservice - Production (optimized compiled image)
  auth-ms-prod:
    container_name: auth-ms-prod
    restart: unless-stopped
    build:
      target: prodimage
      context: .
    ports:
      - "${PORT_PROD}:${PORT_PROD}"
    environment:
      - HOST=${HOST}
      - PORT=${PORT_PROD}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - REDIS_URL=${REDIS_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_MAIL=${RESEND_FROM_MAIL}
    depends_on:
      - postgres-auth-db
      - redis-auth-db

volumes:
  postgres_data:
  redis_data:
